name: pubpy

on:
  push:
    tags:
      - 'v1.0.0'  # Triggers only on version tags (e.g., v1.0.0)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'  # Specify the Python version you want

    - name: Install dependencies
      run: |
        pip install pubpy
        pip install git+https://github.com/haihuilab/pubpy



